"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""
import csv
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from pprint import pprint

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'

LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = True


STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

BUS_STATION_CSV = os.path.join(BASE_DIR, 'data.csv')

SECRET_KEY = 'put your secret here'
DEBUG = True

try:
    from .settings_local import *
except ImportError:
    pass


FILES_PATH = os.path.join(os.getcwd(), 'data.csv')
ITEMS_ON_PAGE = 10


#  ЕСЛИ ЗАПУСТИТЬ settings.py С ДАННЫМ КУСКОМ КОДА, CONTENT СФОРМИРУЕТСЯ И ВЫВКДКТСЯ НА ЭКРАН
#
# def get_content(path):
#     colum_name = ['ID', 'Name', 'Street', 'District']
#     content = []
#
#     with open(path, newline='', encoding='cp1251') as csvfile:
#         file_reader = csv.DictReader(csvfile, delimiter=",")
#
#         for elem in file_reader:
#             content_elem = {}
#             for colum in colum_name:
#                 content_elem[colum] = elem[colum]
#             content.append(content_elem)
#         return content

# CONTENT = get_content(FILES_PATH)
# pprint(CONTENT)
